version: '3.1'

services:  
  database:
    image: arm64v8/mysql:oracle
    restart: always
    user: mysql
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: test_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    secrets:
      - db_password
    volumes:
      - ./database/db:/var/lib/mysql

  website:
    build: website/.
    ports:
      - 80:80
      - 443:443
    secrets:
      - db_password
    volumes:
      - ./website/html:/var/www/html/

secrets:
  db_password:
    file: ./MYSQL_DB_PASSWORD