version: '3.1'

services:
  mssqldb: 
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - 6666:1433
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD_FILE: /run/secrets/mssql_sa_password
      MSSQL_PID: Developer
    secrets:
      - mssql_sa_password
    volumes:
      - ./database/mssqldb:/var/opt/mssql

  database:
    image: arm64v8/mysql:oracle
    #image: mysql:oracle
    restart: always
    user: mysql
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: test_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_db_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    secrets:
      - mysql_db_password
    volumes:
      - ./database/db:/var/lib/mysql

  website:
    build: website/.
    ports:
      - 80:80
      - 443:443
    secrets:
      - db_password
    volumes:
      - ./website/html:/var/www/html/

secrets:
  mysql_db_password:
    file: ./MYSQL_DB_PASSWORD
  mssql_sa_password:
    file: ./MSSQL_SA_PASSWORD